### ISSUE TITLE
NaCl stops coming out of shaker before saturation

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/beers-law-lab#174] opened 2016-05-23 18:48 UTC
Test device: Schrodinger

Operating System: Win 8

Browser: Chrome

Problem description: When the container has the full 1 Liter of water in it, the shaker will sometimes stop dispensing NaCl before the solution becomes saturated. This doesn't happen with any other solute. 

Steps to reproduce: Select NaCl, fill the container full with water, and shake until no more comes out of the shaker. Most likely, on the first try, it will stop dispensing before it becomes saturated (saturates at 6.150 mol/L). If it doesn't happen on the first try, draining some solution, then adding water and shaking again may cause it to stop before it is saturated. But, this method sometimes also fixes the problem. If it stopped dispensing before saturation, and you drain, refill, and shake again, it may become saturated.

Severity: Low

Screenshots:
![concentration](https://cloud.githubusercontent.com/assets/11947677/15480780/80d5f328-20e4-11e6-9616-a4aa2e691e86.gif)

Troubleshooting information (do not edit):
Name: ‪Beer's Law Lab‬
URL: http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.4.0-rc.1/beers-law-lab_en.html
Version: 1.4.0-rc.1 2016-05-23 15:41:35 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36
Language: en-US
Window: 1920x973
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"7d27130a","branch":"master"},"axon":{"sha":"9bf8f88c","branch":"master"},"babel":{"sha":"37077fff","branch":"master"},"beers-law-lab":{"sha":"27ef4131","branch":"1.4"},"brand":{"sha":"bb1cfcc6","branch":"master"},"chipper":{"sha":"22a9ffe2","branch":"master"},"dot":{"sha":"04efe0bc","branch":"master"},"joist":{"sha":"3931eb76","branch":"master"},"kite":{"sha":"dce9765e","branch":"master"},"nitroglycerin":{"sha":"ad3cb990","branch":"master"},"phet-core":{"sha":"c48bf320","branch":"master"},"phetcommon":{"sha":"eab7fb7f","branch":"master"},"scenery":{"sha":"d36b3155","branch":"master"},"scenery-phet":{"sha":"2b60b8e4","branch":"master"},"sherpa":{"sha":"e1b3c84b","branch":"master"},"sun":{"sha":"6f66368f","branch":"master"},"tandem":{"sha":"29f64233","branch":"master"}}

related to phetsims/tasks#600 and phetsims/tasks#602

**Comment by ariel-phet** [comment] 2016-05-23 19:00
@pixelzoom marking as low priorty since obviously function builder takes precedence and this is a feature enhancement and not a bug in the published sim.

**Comment by alynne-phet** [comment] 2016-05-23 19:52
@pixelzoom @brroberts1231 Similar issue seen on Ipad 2 (IOS 8.4.1). Shaker completely stopped dispensing NaCl when the solution was not saturated (stopped dispensing at 6.055 mol/L).

**Comment by pixelzoom** [comment] 2016-05-23 20:51
Related to RC test task https://github.com/phetsims/tasks/issues/600.

The issue is that the sim model is only capable of dispensing up to 6 moles of solute from the shaker or beaker. And according to the specification provided by @amyh-phet  in https://github.com/phetsims/beers-law-lab/issues/169#issuecomment-218865254, saturation occurs at the maximum concentration of 6.15 moles.  So within the limitations of the current model, it's impossible to reach saturation before running out of solute in the shaker or dropper.

@amyh-phet how do you want to proceed?

**Comment by pixelzoom** [comment] 2016-05-23 20:57
Additional thoughts...

(1) We should confirm that 6.15 moles is indeed the saturation point for NaCl. When gathering specifications, I'm not sure if it was clear that "max concentration" was the concentration at which precipitation occurs.

(2) I could investigate increasing the amount of solute in the shaker and dropper, but I'm not sure what other problems that might cause. (Note to self: see SOLUTE_AMOUNT_RANGE in ConcentrationModel.)

**Comment by pixelzoom** [comment] 2016-05-23 21:01
@brroberts1231 For future reference... 

(1) When creating an issue related to an RC test task, please indicate the task issue(s) in your comments. That will automatically link the issue to the test task issue. (I've linked this issue to the test tasks above).

(2) When verifying a specific GitHub issue, the usual procedure is to report problems in the original issue (https://github.com/phetsims/beers-law-lab/issues/169 in this case).  Creating a new issue makes it a bit more difficult to track.  No need to fix anything here, just FYI.

**Comment by pixelzoom** [comment] 2016-05-23 21:02
This issue is related to new feature #169 (add solute Sodium Chloride).

**Comment by pixelzoom** [comment] 2016-05-23 21:03
@brroberts1231 Ah sorry, I see that you did indeed link to the task issues below the troubleshooting info in the first comment.

**Comment by pixelzoom** [comment] 2016-05-23 21:06
Info in this issue moved to https://github.com/phetsims/beers-law-lab/issues/169, closing.

**Closed by pixelzoom** 2016-05-23 21:06 UTC
Labels: priority:4-low, type:bug
