### ISSUE TITLE
Incorrect pointer areas for Solute radio buttons

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#317] opened 2023-01-31 17:53 UTC
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/889. Not seen in published
The pointer area for the solids shaker extends beyond the toolbox, which leads to slightly odd behavior, where you can click outside the toolbox and still select the shaker. This is mor a concern for the mouse area rather than the touch area.
Some locales have this issue with the dropper as well.

**Visuals**
<img width="397" alt="offleft" src="https://user-images.githubusercontent.com/41024075/215842162-237f2416-bbd9-413c-a504-b0b868686d6c.png">
<img width="363" alt="locales" src="https://user-images.githubusercontent.com/41024075/215842939-75a714bb-f412-4972-9cd2-19cd1c3e8a4d.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Beer's Law Lab‬
URL: https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-dev.8/phet/beers-law-lab_all_phet.html?showPointerAreas
Version: 1.7.0-dev.8 2023-01-27 19:51:37 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1280x649
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment] 2023-01-31 21:54
This is due to a bug in AquaRadioButtonGroup.  It's doing the wrong thing for horizontal orientation.  See https://github.com/phetsims/sun/issues/825.

**Comment by pixelzoom** [comment] 2023-01-31 21:58
https://github.com/phetsims/sun/issues/825 has been addressed. And in the above commit, I tweaked the pointer areas for this specific case.  See screenshot below. 

@KatieWoe please review in master, close if OK.

<img width="460" alt="screenshot_2223" src="https://user-images.githubusercontent.com/3046552/215893078-62d34f5e-9803-4bff-9d73-b940c1781e4e.png">

**Comment by KatieWoe** [comment] 2023-01-31 22:21
Looks good in master

**Comment by Nancy-Salpepi** [comment] 2023-02-06 21:30
For https://github.com/phetsims/qa/issues/894:
This is fixed in master, but I still see the issue in rc.1.

**Comment by pixelzoom** [comment] 2023-02-06 22:01
Hmmm... The fix was done and confirmed in master during a dev test, so there was no release branch to cherry-pick to.   I'll investigate...

**Comment by pixelzoom** [comment] 2023-02-06 22:13
This is definitely still fixed in master.  I wasn't involved in creating the 1.7 release branches, but something is very wrong.  I've reopened all of the issues that I addressed during dev testing, to confirm whether they are fixed in 1.7.0-rc.1.

Assigning to @samreid @matthew-blackman to investigate what went wrong here.

**Comment by pixelzoom** [comment] 2023-02-08 15:18
@KatieWoe @Nancy-Salpepi please reconfirm in 1.7.0-rc.2 for https://github.com/phetsims/qa/issues/894.

**Comment by Nancy-Salpepi** [comment] 2023-02-08 15:46
This is fixed in 1.7.0-rc.2. It looks like the screenshot in https://github.com/phetsims/beers-law-lab/issues/317#issuecomment-1411124006

**Closed by Nancy-Salpepi** 2023-02-08 15:46 UTC
Labels: type:bug, status:ready-for-review
