### ISSUE TITLE
CT unexpected number of particles removed: expected 3, removed 0

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#286] opened 2022-04-12 14:50 UTC
```
beers-law-lab : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/phet-io-wrappers/state/?sim=beers-law-lab&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1649728257423%22%2C%22timestamp%22%3A1649735346764%7D
Uncaught Error: Uncaught Error: Assertion failed: unexpected number of particles removed: expected 3, removed 0
Error: Assertion failed: unexpected number of particles removed: expected 3, removed 0
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/assert/js/assert.js:25:13)
at Precipitate.removeParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:96:15)
at Precipitate.updateParticles (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:64:12)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/beers-law-lab/js/concentration/model/Precipitate.js:39:60
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:147:14)
at DerivedProperty.getDerivedPropertyListener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/DerivedProperty.js:112:13)
at TinyProperty.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/TinyEmitter.js:68:9)
at NumberProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1649728257423/chipper/dist/js/axon/js/Property.js:218:23)
id: Bayes Chrome
Snapshot from 4/11/2022, 7:50:57 PM
```

**Comment by pixelzoom** [comment] 2022-04-12 14:52
Duplicate of https://github.com/phetsims/beers-law-lab/issues/284.

**Closed by pixelzoom** 2022-04-12 14:52 UTC
Labels: type:automated-testing
