### ISSUE TITLE
intermediate updates of ATDetector.valueProperty result in spurious PhET-iO messages

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#154] opened 2016-02-01 16:39 UTC
@phetsims/sarah-perez said:

> I did notice something strange that I thought you might want to know about. When the solution is changed (and thus the wavelength is changed to the peak absorption wavelength for that solution), there are three "absorption detector events" in a row as if the value changed 3 times. 

When I turned the detector on and changed solution, I also saw spurious messages:

![image](https://cloud.githubusercontent.com/assets/679486/12723647/8b1f3a80-c8c7-11e5-9c7f-9261aa8fae60.png)

I'm creating this as an issue in beers-law-lab instead of together because I suspect there is a transient property value that is sending out a message. The priority of this issue should be based on ease of solving the problem, if easy to solve, would be good to solve before next publication.  If difficult, then it can wait.  @pixelzoom any ideas what might be causing this?

**Comment by pixelzoom** [comment] 2016-02-01 18:14
@ariel-phet instructed me to spend some time investigating this.

**Comment by samreid** [comment] 2016-02-01 18:15
I'm available for collaboration at the moment if you'd like me to tag along.

**Comment by pixelzoom** [comment] 2016-02-01 18:18
This is nowhere near the top of my priority stack yet.

**Comment by pixelzoom** [comment] 2016-02-01 22:16
@phetsims/sarah-perez said:

> When I turned the detector on

How did you turn the detector on? It's on all the time.  Did you mean that you selected 'Transmittance' or 'Absorbance' with one of the detector's radio buttons? Or something else?

**Comment by pixelzoom** [comment] 2016-02-01 22:16
Ah... Looks like that is @samreid saying "When I turned the detector on".  @samreid ?

**Comment by samreid** [comment] 2016-02-01 22:20
My apologies, I should have said "put the detector in the path of the beam".

**Comment by pixelzoom** [comment] 2016-02-01 22:27
@samreid I'll need some assistance reproducing the "spurious messages".  I don't see anything like that in the console when running a built version with `?togetherEvents.log=console&phet-io-standalone`.

**Comment by samreid** [comment] 2016-02-01 22:28
togetherEvents.log=lines is the abbreviated "human readable" form.  I'm working a bit longer, skype me if you want to join forces.

**Comment by pixelzoom** [comment] 2016-02-01 22:40
Got it, messages reproduced.

**Comment by pixelzoom** [comment] 2016-02-01 23:15
There are indeed some intermediate states here.  And I actually see 3 "valueProperty changed" messages in some cases, eg:

![screenshot_02](https://cloud.githubusercontent.com/assets/3046552/12734611/efa988ac-c8fe-11e5-9564-b424288a2855.png)

The ATDetector.valueProperty is a DerivedProperty. One of its dependencies is Absorbance.absorbanceValue, which has multiple dependencies that update when the solution changes.  This will be some fun to unravel.  I estimate 2-3 hours. @ariel-phet do you want me to proceed?

**Comment by pixelzoom** [comment] 2016-02-01 23:52
Looks like `Beam.fillProperty` (the beam color, with transparency determined by transmittance) probably has this same issue (invalid intermediate states) but is not currently instrumented for PhET-iO.  I'm guessing that it's unlikely that RGBA values of the beam will be of interest in the PhET-iO data stream, but figured I should point it out.  If `fillProperty` were instrumented, we'd need to address this issue in Beam too.

**Comment by sperez8** [comment] 2016-02-01 23:56
Sorry I was away from my emails and couldn't respond but yes the messages I
got were similar to the ones above.



*Sarah Perez, M.Sc*
Dynamic Assessment Research Coordinator
Centre for Teaching, Learning and Technology at UBC
www.spzfolio.com
604-842-6751

**Comment by pixelzoom** [comment] 2016-02-01 23:58
In both ATDetector and Beam, the issue is that when the solution changes, there are 3 dependencies that change: solution, concentration (set to the new solution's concentration), and wavelength (set to lambdaMax for the new solution).  The last 2 (concentration and wavelength) can be varied by user, so are independent from solution, except when the solution is changed.

**Comment by pixelzoom** [comment] 2016-02-02 19:52
@ariel-phet In https://github.com/phetsims/beers-law-lab/issues/154#issuecomment-178249246, I estimated 2-3 hours for further investigation and possible fix. Do you want me to proceed?

**Comment by ariel-phet** [comment] 2016-02-03 17:25
@sperez8 I should mention that @pixelzoom's time is at a serious premium at the moment. Unless you feel that this work is "mission critical" to your study and cannot be worked around, we are going to defer work on this issue for the moment

**Comment by ariel-phet** [comment] 2016-02-03 17:26
Clearing assignee for the moment

**Comment by sperez8** [comment] 2016-02-03 19:00
Definitely not a missions critical item. I can work around it.

**Comment by phet-steele** [comment] 2016-03-04 22:19
@samreid @pixelzoom, the same thing is occurring with precipitateAmount, causing wacky numbers in the calculations for soluteGrams:

![badintermediate](https://cloud.githubusercontent.com/assets/5863899/13541854/25589a2a-e21c-11e5-94fa-2747dd2800c5.PNG)

I'm only writing this comment to point out there are other DerivedProperties (precipitate amount is a DerivedProperty) that have problems, but if I need to make a separate issue to clarify how this works, I will.

**Comment by pixelzoom** [comment] 2016-03-04 22:27
This is a general issue that will occur with *any* DerivedProperty.  If N dependency changes simultaneously, then the derivation function of a DerivedProperty fires N times, not 1 time.  If N>1, then the DerivedProperty is guaranteed to have invalid intermediate states. @samreid Should this be moved to a more general issue in phet-io?

**Comment by samreid** [comment] 2016-03-05 04:42
> If N>1, then the DerivedProperty is guaranteed to have invalid intermediate states.

What about this derived property?

```js
var massProperty = new Property(1);
var velocityProperty = new Property(2);
var momentumProperty = new DerivedProperty([massProperty,velocityProperty],function(mass,velocity){
  return mass * velocity;
}); // Initially the momentum is 1*2=2, checks out

// We want to change mass and velocity simultaneously but we can't given these constraints so we change one at a time.
massProperty.value = 3; // 3*2=6, checks out
velocityProperty.value = 4; // 3*4=12, checks out.
```
So it appears there are some N>1 derived properties that are not guaranteed to have invalid intermediate states.

**Comment by samreid** [comment] 2016-03-05 04:43
> @samreid Should this be moved to a more general issue in phet-io?

Let's discuss it here a bit more before moving...

**Comment by pixelzoom** [comment] 2016-03-07 21:59
Ah yes, my generalization in https://github.com/phetsims/beers-law-lab/issues/154#issuecomment-192499864 is indeed incorrect.

**Comment by phet-steele** [comment] 2016-05-23 20:25
@pixelzoom the `precipitateAmountProperty` is calculated over and over again while draining a solution. The value fluctuates up and down, causing the visual effect of precipitate appearing and disappearing while draining. The capture rate on this video is lower than I'd like, so it's not as dramatic looking:
![bll01](https://cloud.githubusercontent.com/assets/5863899/15483465/08973b70-20f2-11e6-89bf-043ad98ec5b0.gif)

**Comment by pixelzoom** [comment] 2016-05-24 16:12
@phet-steele The issue you've reported about is different than the "intermediate value" issue.  First of all, it's visible to the user, while the intermediate values are not.   And it's not really an intermediate value - the value of precipitateAmount does need to change when the volume changes.  The precipitate particles are changing because precipitateAmount changes very slightly due to Javascript precision; and whenever the value changes, particles are added/removed from a stack.   So.... I've moved this to issue #175.

**Comment by pixelzoom** [comment] 2017-08-29 17:15
So we identified that this is being caused because a DerivedProperty goes through some intermediate states when >1 of its dependencies changes.  And a sim *in general* can be in an intermediate state until changes to dependencies finish cascading.    This problem is not specific to Beer's Law Lab, and I have no suggestion for how to address it in the general case. 

Assigning to @samreid to decide how to proceed, since this seems like yet-another big general PhET-iO issue.  If you think this issue is worth pursuing, then please move this issue out of beers-law-lab, and create a general issue.

**Comment by samreid** [comment] 2017-09-08 16:21
I created an axon issue, @pixelzoom can you please review the new issue and close this one if it is ready to close?

**Comment by pixelzoom** [comment] 2017-09-08 16:24
axon issue looks perfect, closing.

**Closed by pixelzoom** 2017-09-08 16:24 UTC
Labels: dev:phet-io
