### ISSUE TITLE
Problem with floating solute labels

### ISSUE THREAD

**Issue by brroberts1231** [phetsims/beers-law-lab#116] opened 2015-10-29 22:46 UTC
Test device: Dell 

Operating System: Win 10

Browser: Edge 20.10240.16384.0

Problem description: In the concentration tab of the sim, I noticed that when you change the solute, the text for the chemical formula that would be on the dropper or shaker(whichever one is not selected at the time) will be floating where the unselected one would be. When you switch between the dropper and shaker, everything is normal and the text is where it is supposed to be, until you switch substances again, and the text will be floating where the previous object was before switching between solid and solution.

Steps to reproduce: In the concentration side of the sim, choose any new solute from the dropdown menu, and you will notice that there is vertical text floating where the dropper would be if it were selected. Press the solution button to select the dropper, and then change the solute again. There will now be diagonal floating text where the shaker previously was.

Severity:

Screenshots: Switched from drink mix to Cobalt(II) Nitrate:
![beerslawfloatingtext](https://cloud.githubusercontent.com/assets/11947677/10833981/53c22040-7e5b-11e5-962a-f3380c3ab624.JPG)
Then selected the dropper, everything is normal here:
![beerslawfloatingtext2](https://cloud.githubusercontent.com/assets/11947677/10834023/bc32bfcc-7e5b-11e5-88aa-442d6163f48a.JPG)
Then selected a new substance, and there is text floating where the shaker was:
![beerslawfloatingtext3](https://cloud.githubusercontent.com/assets/11947677/10834111/5fad2606-7e5c-11e5-952e-63d18fd2a6b8.JPG)

Troubleshooting information (do not edit):

Name: ‪Beer's Law Lab

URL: http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.0-rc.1/beers-law-lab_en.html

Version: 1.3.0-rc.1 2015-10-28 17:08:18 UTC

Features missing: touch

Flags: pointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240

Language: en-US

Window: 1536x710

Pixel Ratio: 1.25/1

WebGL: WebGL 0.95

GLSL: WebGL GLSL ES 0.95

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 16384x16384

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"ea354263","branch":"master"},"babel":{"sha":"d352eb6d","branch":"master"},"beers-law-lab":{"sha":"79f505c0","branch":"1.3"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"778caa53","branch":"master"},"dot":{"sha":"03415417","branch":"master"},"joist":{"sha":"8d87df6c","branch":"master"},"kite":{"sha":"7f2df7e9","branch":"master"},"nitroglycerin":{"sha":"88cfd142","branch":"master"},"phet-core":{"sha":"6eab326e","branch":"master"},"phetcommon":{"sha":"0e4754fe","branch":"master"},"scenery":{"sha":"1606cafc","branch":"master"},"scenery-phet":{"sha":"33f31628","branch":"master"},"sherpa":{"sha":"f3cf6285","branch":"master"},"sun":{"sha":"f678dd20","branch":"master"},"tandem":{"sha":"c54f1082","branch":"master"}}

**Comment by pixelzoom** [comment] 2015-10-30 17:02
Problem appears to be Edge-specific, I can't reproduce on other platforms.  This sounds like it's related to the fix for text on Edge.  Assigning to @jonathanolson with high priority.

**Comment by jonathanolson** [comment] 2015-10-30 17:08
Reproduced. Also able to reproduce on Chrome with ?rootRenderer=canvas.

**Comment by pixelzoom** [comment] 2015-10-30 17:10
I can also reproduce on Mac OS X 10.5.5 + Chrome with `?rootRenderer=canvas`.

**Comment by pixelzoom** [comment] 2015-10-30 17:12
Also reproduced on Mac OS X 10.5.5 with Safari and Firefox and `?rootRenderer=canvas`.  So this would appear to be a general problem with the canvas renderer, rather than Edge specific.

**Comment by jonathanolson** [comment] 2015-10-30 17:22
> So this would appear to be a general problem with the canvas renderer, rather than Edge specific.

Yup. The text drawables for the SubSupText are incorrectly marked as visible (Scenery-internal issue). Investigating why, and how to fix.

**Comment by jonathanolson** [comment] 2015-10-30 20:01
Applied fix, @pixelzoom, are you able to verify with the rootRenderer=canvas test?

**Comment by pixelzoom** [comment] 2015-10-30 20:38
All is well on Mac OS X 10.10.5 with Chrome, Safari and FF.

@jonathanolson said he tested on Edge. But I'm not clear on whether this was tested on iOS and IE, so back to him for verification.

**Comment by jonathanolson** [comment] 2015-10-30 20:46
Build off of master now doesn't have the bug on Edge (Win10), iOS 9.1 and IE11 (Win7).

**Closed by jonathanolson** 2015-10-30 20:46 UTC
Labels: high priority

**Comment by pixelzoom** [comment] 2015-10-30 20:52
Note that this fix will require using master for the next RC.  Since it's in the Concentration screen, it affects the RCs for both beers-law-lab and concentration.
