### ISSUE TITLE
change "fixed" string key to "preset"

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#146] opened 2016-01-01 03:47 UTC
While working on https://github.com/phetsims/beers-law-lab/issues/145 I noticed a mismatch between the tandem name and the name of the associated string key:

```js
        new AquaRadioButton( this.variableWavelengthProperty, false,
          new Text( fixedString, {
            font: new PhetFont( 18 ),
            fill: 'black'
          } ), {
            radius: BLLConstants.RADIO_BUTTON_RADIUS,
            tandem: tandem.createTandem( 'presetWavelengthRadioButton' )
          } ),
```

It appears the string key for "preset" is "fixed":

```js
  "fixed": {
    "value": "preset"
  },
```

This discrepancy stands out because there are so few other discrepancies in the sim.  Bringing this to @pixelzoom's attention in case he wishes to address it.

**Comment by pixelzoom** [comment] 2016-01-05 00:31
The label on the wavelength control was changed from "fixed" (Java version) to "preset" (HTML5 version).  Unfortunately, the string key didn't get changed.  Changing that key now is problematic, since the published version of the sim is translatable and has 10 published translations.  

So I think we should live with this for now.  People using the PhET-iO API won't be looking at the string files (and visa versa) so this is really just a small wart in the implementation.   If we want to correct it, then the next time the sim is published, we can (1) change the key in the English string file, and (2) update the key in all existing translations.

**Comment by pixelzoom** [comment] 2016-01-05 00:32
I'm going to mark this as deferred, and we can address it next time the sim is published.

**Comment by pixelzoom** [comment] 2016-02-04 18:48
I changed the English string key and related .js files in master. 

According to @jbphet, the existing translations in babel should not be changed until immediately after a new version is published to the PhET website.  This is because Rosetta looks at the currently published English version for string keys. 

So leaving this issue open so that I remember to update translations immediately after the next publication.

**Comment by pixelzoom** [comment] 2016-02-10 16:11
Mentioning @samreid so that he's aware of this issue when publishing versions of this sim.  Until a public version is published to the PhET website, babel translations are out of sync this string key in master.

**Comment by samreid** [comment] 2016-02-10 16:16
Thanks!

**Comment by pixelzoom** [comment] 2016-02-29 18:53
Apparently there was a maintenance release (1.3.3) that occurred while I was on vacation the did not consider this issue.  I think we're OK for now since I hadn't merged the fix into the 1.3 branch yet. But in the future, we need to check open issues before publishing.

**Comment by pixelzoom** [comment] 2016-05-19 16:48
Assigned to me, since publication is imminent.

**Comment by pixelzoom** [comment] 2016-05-23 15:55
For regression testing, please verify that "preset" is displayed on the wavelength slider in the "Beer's Law" screen.  Note this in a comment. Leave this issue assigned to me so that I can make changes to Rosetta/babel when the sim is re-published.

**Comment by phet-steele** [comment] 2016-05-23 16:28
@pixelzoom, preset is certainly there on everything!

**Comment by pixelzoom** [comment] 2016-05-23 16:33
Setting label to "in progress" to remind me to do Rosetta/babel followup.

**Comment by pixelzoom** [comment] 2016-06-20 14:37
Published in Beer's Law Lab 1.4.0 and Concentration 1.3.0.

**Comment by pixelzoom** [comment] 2016-06-30 19:10
Done. Checked in Rosetta with @jbphet after publishing.

**Comment by pixelzoom** [comment] 2016-06-30 19:11
Babel was updated in https://github.com/phetsims/babel/commit/ba33fbfb2f3f3d997bc69d6b5ff89954d0522df2.

**Closed by pixelzoom** 2016-06-30 19:10 UTC
Labels: status:in-progress
