### ISSUE TITLE
Drag interactions aren't interrupted with Reset All on the iPad

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/beers-law-lab#316] opened 2023-01-31 14:10 UTC
**Test device**
ipad 9th generation

**Operating System**
16.2

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/889 and https://github.com/phetsims/qa/issues/891, pressing Reset All does not interrupt me holding an object with another finger. This happens with the following items on the Concentration Screen:  the faucet, shaker, evaporation slider, and concentration probe. On the Beer's Law screen: the ruler, probe, concentration slider, and cuvette arrow.

Also seen in published. 

**Steps to reproduce**
Here is an example:
1. On the iPad, on the Concentration screen, move and hold the Concentration Probe with one finger
2. With another finger, press the Reset All button
3. Wiggle your first finger slightly--the probe will move back to that position

**Visuals**

https://user-images.githubusercontent.com/87318828/215782532-27093e0e-0f88-4950-9d46-8006592675b4.mov

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Laboratoire Loi de Beer-Lambert‬
URL: https://phet-dev.colorado.edu/html/beers-law-lab/1.7.0-dev.8/phet/beers-law-lab_all_phet.html
Version: 1.7.0-dev.8 2023-01-27 19:51:37 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language: en-US
Window: 1536x781
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment] 2023-01-31 22:10
Fixed in master. @Nancy-Salpepi please review and close if OK.

**Comment by pixelzoom** [comment] 2023-02-06 22:17
Reopening to confirm in https://github.com/phetsims/qa/issues/894. It looks like changes I made during dev testing did not get into the 1.7 release branch.

@KatieWoe can you please test to see if this looks correct in 1.7.0-rc.1.

@samreid @matthew-blackman FYI.

**Comment by pixelzoom** [comment] 2023-02-06 22:42
Confirmed that this change is in 1.7, inspect code.  Closing.

**Closed by pixelzoom** 2023-02-06 22:42 UTC
Labels: type:bug, type:multitouch, status:ready-for-review
