### ISSUE TITLE
Particles drop performance

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#209] opened 2017-09-09 15:45 UTC
From https://github.com/phetsims/phet-io-wrappers/issues/23

Carried from https://github.com/phetsims/phet-io/issues/414 into this repo

@phet-steele said:

Precipitate and shaker particle data streams cause significant loses in performance. I can reliably cause an unresponsive web page on Win 10 browsers after reaching saturation. This is a pretty small amount of precip. being made, mind you....I can do much worse things 😈

https://drive.google.com/file/d/0B3HJopSo_QqLMndYQkdxcFoxelk/view?usp=sharing

For phetsims/phet-io#408.

and then:

@samreid particles are significantly affecting this sim's performance in instance proxies. Can anything at all be done about this? It hardly takes the addition of any particles to kill the browser.

**Comment by samreid** [comment] 2017-09-09 15:46
In my opinion, each solute particle doesn't need to have a decorator in instance proxies.  It may still need to be instrumented for state though (using our current save/load paradigm).

**Comment by pixelzoom** [comment] 2017-09-11 16:21
Agreed, representing each particle in instance proxies is overkill.  

As for saving... I'm not convinced that saving/restoring individual particles is the way to go, or that the current implementation supports this well.  There are lots of other way that "precipitate" could have been implemented. For example: have 1 model object (Precipitate) that has the state of where its particles are, and the view would be responsible for rendering Precipitate as multiple instances of Particle Node, or perhaps even as PrecipitateNode that draws all particles using 1 path.   

The more general point here is that PhET-iO requirements (like what aspects of the precipitate need to be customizable, serializable, etc.) need to be considered during design, because they impact how the sim is implemented.

**Comment by samreid** [comment] 2017-09-12 02:59
I'm having trouble killing performance on my Mac browsers or in my VirtualBox+IE by shaking out particles, but it would be straightforward to omit TShakerParticle, TPrecipitateParticle from instance proxies.  The original bug report was from May 5, 2016 and it would be good to confirm it is still a problem before working on it more.  @phet-steele can you replicate this problem on master?

**Comment by phet-steele** [comment] 2017-09-27 19:35
Performance suffers pretty badly on an iPad 2 right out of the gate...so not really related to high amounts of precipitate in that case.

I also cannot ruin performance on my Mac with current master (yay!). Precip instances look to be properly disposed on reset, removal, etc., so that makes it a bit hard to create the thousands of particles I used to be able to.

That being said, I do lose performance quite handily after doing this:

1. master BLL + Instance Proxies, Concentration screen
2. Drain the beaker.
3. Shake particles, and keep shaking until some hit the bottom of the beaker.
4. Quickly, while some particles are still falling (and some are on the bottom too), start adding water to the beaker.
4. Drain the beaker and repeat if no errors were thrown.

I get hundreds of these:
```
Uncaught Error: Assertion failed: mismatched messageIndex, possible start/end mismatch
    at window.assertions.assertFunction (assert.js:22)
    at Object.end (phetioEvents.js?bust=1506540405566:175)
    at Array.endedCallback (toEventOnEmit.js?bust=1506540405566:29)
    at Emitter.emit (Emitter.js?bust=1506540405566:169)
    at DerivedProperty._notifyListeners (Property.js?bust=1506540405566:206)
    at DerivedProperty._setAndNotifyListeners (Property.js?bust=1506540405566:193)
    at DerivedProperty.set (Property.js?bust=1506540405566:140)
    at Array.listener (DerivedProperty.js?bust=1506540405566:67)
    at Emitter.emit2 (Emitter.js?bust=1506540405566:206)
    at NumberProperty._notifyListeners (Property.js?bust=1506540405566:204)
```

@samreid  The performance drop is likely due to the massive cascade of errors this creates, and not due to the number of precip particles present. So feel free to close this and create a new issue for this error.

**Comment by samreid** [comment] 2017-10-10 06:40
There is a new `log` query parameter to help diagnose `mismatched messageIndex, possible start/end mismatch` we might be able to use.  But several emitters changed recently, we should see if we can replicate this problem in master.

**Comment by samreid** [comment] 2017-10-10 16:27
I tried the instructions from https://github.com/phetsims/beers-law-lab/issues/209#issuecomment-332631768 on mac chrome and 4/5 times it was fine and on the 5th time it threw an assertion error that the `percentConcentration` was -2000 or so.

@phet-steele can you double check on master at the moment and if this is replicable?

**Comment by phet-steele** [comment] 2017-10-10 16:39
@samreid, broke it first try with steps in  https://github.com/phetsims/beers-law-lab/issues/209#issuecomment-332631768. My `percentConcentration` was 212...I think you beat me! Throws this assertion:
```
Uncaught Error: Assertion failed
    at window.assertions.assertFunction (/assert/js/assert.js:22)
    at ConcentrationSolution.js?bust=1507652942716:112
    at Array.listener (DerivedProperty.js?bust=1507652942716:67)
    at Emitter.emit2 (Emitter.js?bust=1507652942716:205)
    at DerivedProperty._notifyListeners (Property.js?bust=1507652942716:207)
    at DerivedProperty._setAndNotifyListeners (Property.js?bust=1507652942716:195)
    at DerivedProperty.set (Property.js?bust=1507652942716:142)
    at Array.listener (DerivedProperty.js?bust=1507652942716:67)
    at Emitter.emit2 (Emitter.js?bust=1507652942716:205)
    at DerivedProperty._notifyListeners (Property.js?bust=1507652942716:207)
```

**Comment by samreid** [comment] 2017-10-10 16:41
It would be good for @pixelzoom to look into the transient out of bounds concentration issue.  @pixelzoom after investigating that part, please reassign to me to look into whether the `mismatched messageIndex` is still happening.

**Comment by pixelzoom** [comment] 2017-10-11 14:53
@samreid said:
> It would be good for @pixelzoom to look into the transient out of bounds concentration issue.

Before I do anything here....  Step 1 of https://github.com/phetsims/beers-law-lab/issues/209#issuecomment-332631768 says:

> 1. master BLL + Instance Proxies, Concentration screen

Has this been reproduced when not running with Instance Proxies?  If so, then let's break this out into a separate issue.

**Comment by pixelzoom** [comment] 2017-10-11 14:55
Answered my own question.  Yes, this can be reproduced without instance proxies.

**Comment by samreid** [comment] 2017-10-16 01:56
On hold until #210 is complete.

**Comment by pixelzoom** [comment] 2017-10-23 17:28
@samreid #210 is completed (pending verification by @phet-steele), so you may proceed with this issue.

**Comment by phet-steele** [comment] 2017-10-23 18:15
@samreid go ahead.

**Comment by pixelzoom** [comment] 2017-10-23 18:45
Btw... #210 should be totally unrelated to the "mismatched messageIndex" failures reported in https://github.com/phetsims/beers-law-lab/issues/209#issuecomment-332631768.

**Comment by samreid** [comment] 2017-11-11 02:51
OK It seems the next step for this issue is to see if the mismatched messageIndex is still occurring now that #210 is fixed.  I tried the instructions in https://github.com/phetsims/beers-law-lab/issues/209#issuecomment-332631768 5 times on my Mac/Chrome and didn't see any errors in the console or performance degradation.  @phet-steele can you please take a look?

**Comment by phet-steele** [comment] 2017-11-14 18:26
Also no errors or performance concerns here.

**Comment by phet-steele** [comment] 2018-06-07 18:24
> I also cannot ruin performance on my Mac with current master (yay!). Precip instances look to be properly disposed on reset, removal, etc., so that makes it a bit hard to create the thousands of particles I used to be able to.

@samreid @pixelzoom the quote I said above looks to not be true anymore. I tried BLL studio on master (and 1.5.6, and 1.6.4) and precip particles are not being removed from the list anymore. Kills performance. What happened?

**Comment by pixelzoom** [comment] 2018-06-07 18:27
No idea, I haven't changed anything related.  But phet-io has been undergoing big changes.  @samreid ?

**Comment by phet-steele** [comment] 2018-06-07 18:47
@samreid, when "checking against the prior published version", which is 1.5.5-phetio, the problem did not exist. So newly introduced again in 1.5.6.

Oh and this is for phetsims/QA/issues/128.

**Comment by samreid** [comment] 2018-06-11 20:41
Testing 1.5.6-phetio, I see 145 instrumented instances on startup.  Then shaking in some particles, it goes to 182 while they are in the air.  Then when they dissolve, it goes back to 145.  I also tried resetting while the particles were in the air, and it correctly went back to 145.  Am I doing this wrong?

**Comment by phet-steele** [comment] 2018-06-11 20:57
@samreid I don't see it in the 1.5.6 branch (don't know why I did earlier), but I do see it in 1.6.4 (and probably master, didn't double check).

**Comment by samreid** [comment] 2018-06-11 21:09
I confirmed the particles are leaking in studio/master.

**Comment by zepumph** [comment] 2018-07-24 18:56
On second thought, dropping priority because I should work on FL thoughtful api first.

**Comment by pixelzoom** [comment] 2020-03-02 21:16
With the conversion to PhetioGroup in #244, there's a possibility that performance may be impacted further.   The previous implementation resulted in at most 1 call to `invalidatePaint` on each call to `step`.  The PhetioGroup implementation results in a call to `invalidatePaint` for each particle added or removed, as well as 1 call to `invalidatePaint` per step if any particle has moved.

**Comment by kathy-phet** [comment] 2020-03-02 21:29
Does each particle need to be instrumented? What if that wasn't part of state, but just populated based on how saturated the solution was?

**Comment by pixelzoom** [comment] 2020-03-02 21:59
We just did a lot of work in #244 to instrument every particle (mainly because it was causing the sim to fail CT), so it will be a shame if we chuck all of this.  But we can certainly revisit when we get to redesign in #230.   Populating based on how saturated the solution is only works for precipitate, and precipitate isn't the main performance issue (it just sits there on the bottom of the beaker).  Shaker particles are the performance issue, because they animate - and don't we also need to address them?

**Comment by kathy-phet** [comment] 2020-03-02 22:08
Those particles dropping transient, so I would be OK with not instrumenting them. I don't think we need to support launching a saved simulation with particles that are actually dropping. @arouinfar - what do you think?

**Comment by samreid** [comment] 2020-03-02 22:16
Please confirm that multiple calls to `invalidatePaint` are actually a performance problem before making any changes based on that assumption.

**Comment by arouinfar** [comment] 2020-03-20 23:14
> Those particles dropping transient, so I would be OK with not instrumenting them. I don't think we need to support launching a saved simulation with particles that are actually dropping. @arouinfar - what do you think?

@kathy-phet agreed.

**Comment by zepumph** [comment] 2020-09-02 23:56
I'm not sure who should be assigned here, perhaps the lead dev to determine if `invalidatePaint` is the cause of the issue?

**Comment by pixelzoom** [comment] 2020-09-03 00:03
This issue (and all PhET-iO related issues) is unassigned and deferred until work resumes on https://github.com/phetsims/beers-law-lab/issues/230  (redesign PhET-iO API).

**Comment by pixelzoom** [comment] 2021-03-15 20:57
Consider using Sprites.js for particles, see #276.

**Comment by KatieWoe** [comment] 2022-12-14 23:44
I tested this on a chrome book and didn't see performance issues.

**Comment by pixelzoom** [comment] 2022-12-15 01:02
Thanks @KatieWoe.  

Since there is no evidence of a performance problem, there is nothing to do, and I'm closing this issue.

**Closed by pixelzoom** 2022-12-15 01:02 UTC
Labels: type:performance, dev:phet-io
