### ISSUE TITLE
Laser initially doesn't fade

### ISSUE THREAD

**Issue by BryceAG** [phetsims/beers-law-lab#118] opened 2015-10-30 20:23 UTC
Test device:
PC, Dell, SCHRODINGER

Operating System:
Windows 8 64-bit

Browser:
Internet Explorer 11

Problem description:
After switching substances, the laser that goes through the solution stays the same color before and after passing through. After adjusting the width of the beaker or the wavelength of the light it will correct itself

Steps to reproduce:
Turn on the laser, switch substance (most noticeable with copper sulfate)

Severity:

Screenshots:

![before](https://cloud.githubusercontent.com/assets/15327201/10857069/159b4306-7f09-11e5-8ca0-e2d8aa0f9022.PNG)
![after](https://cloud.githubusercontent.com/assets/15327201/10857072/193d56f2-7f09-11e5-8788-28819c3ec01b.PNG)

Troubleshooting information (do not edit):
  
Name: ‪Beer's Law Lab‬

URL: http://www.colorado.edu/physics/phet/dev/html/beers-law-lab/1.3.0-rc.1/beers-law-lab_en.html

Version: 1.3.0-rc.1 2015-10-28 17:08:18 UTC

Features missing: touch, fullscreen

Flags: pointerEnabled, msPointerEnabled, pixelRatioScaling

User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; InfoPath.3; rv:11.0) like Gecko

Language: en-US

Window: 1231x617

Pixel Ratio: 1.559999942779541/1

WebGL: WebGL 0.94

GLSL: WebGL GLSL ES 0.94

Vendor: Microsoft (Internet Explorer)

Vertex: attribs: 16 varying: 15 uniform: 512

Texture: size: 8192 imageUnits: 16 (vertex: 16, combined: 32)

Max viewport: 8192x8192

OES_texture_float: true

Dependencies JSON: {"assert":{"sha":"11bc6a6d","branch":"master"},"axon":{"sha":"ea354263","branch":"master"},"babel":{"sha":"d352eb6d","branch":"master"},"beers-law-lab":{"sha":"79f505c0","branch":"1.3"},"brand":{"sha":"8a756e53","branch":"master"},"chipper":{"sha":"778caa53","branch":"master"},"dot":{"sha":"03415417","branch":"master"},"joist":{"sha":"8d87df6c","branch":"master"},"kite":{"sha":"7f2df7e9","branch":"master"},"nitroglycerin":{"sha":"88cfd142","branch":"master"},"phet-core":{"sha":"6eab326e","branch":"master"},"phetcommon":{"sha":"0e4754fe","branch":"master"},"scenery":{"sha":"1606cafc","branch":"master"},"scenery-phet":{"sha":"33f31628","branch":"master"},"sherpa":{"sha":"f3cf6285","branch":"master"},"sun":{"sha":"f678dd20","branch":"master"},"tandem":{"sha":"c54f1082","branch":"master"}}

**Comment by pixelzoom** [comment] 2015-10-30 20:41
Reproduced on Mac OS X 10.10.5 with Safari, Chrome and FF.  So this in now specific to IE.

**Comment by pixelzoom** [comment] 2015-10-30 20:47
This issue is not present in the version published on the website (1.2.3).  It's present in 1.3.0-dev.6 (10/27/2015) but not in 1.3.0-dev.5 (8/25/2015).    And I see no commits any related code (BeamNode) in beers-law-lab since 8/25/2015.    So this smells like something has broken in common code.

@jonathanolson any hunches?

**Comment by pixelzoom** [comment] 2015-10-30 20:51
@jonathanolson said that he reproduced on IE11 Win7.

**Comment by pixelzoom** [comment] 2015-10-30 20:56
To clarify/summarize https://github.com/phetsims/beers-law-lab/issues/118#issuecomment-152647527 ... 

Bisect between 8/25/2015 and 10/27/2015.

**Comment by pixelzoom** [comment] 2015-10-30 21:27
@jonathanolson made the fix in master. I'll patch it into 1.3.

**Comment by pixelzoom** [comment] 2015-10-30 21:46
Fix verified in master and 1.3 branches. This issue was sim-specific, not common-code changes required.

Closing.

**Closed by pixelzoom** 2015-10-30 21:46 UTC
