### ISSUE TITLE
Precipitate not disposed

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#204] opened 2017-08-28 15:06 UTC
From https://github.com/phetsims/phet-io/issues/415

Precipitate particles are not always disposed of correctly, thereby remaining in the state of a sim. To see what I mean follow these steps:
1. From default settings, shake some stuff into solution.
2. Fully evaporate the solution, thereby making many precipitate particles.
3. Pour solvent into the beaker to dissolve the precipitate back into solution.
4. "Launch" the sim. The resulting sim will still display the precipitate particles since they were never removed from the state (you can see the many particles at the bottom of the proxy list):

![precip](https://cloud.githubusercontent.com/assets/5863899/15048330/58e0cd76-12a6-11e6-8f45-b3ded09de03a.PNG)

For phetsims/phet-io/issues/408.

**Comment by pixelzoom** [comment] 2017-08-29 16:59
I have no idea how to reproduce this.  Please enumerate the steps required to reproduce this, including which wrapper to use and how to launch it.

**Comment by pixelzoom** [comment] 2017-08-29 17:09
This looks like a bug that was introduced in https://github.com/phetsims/beers-law-lab/commit/87144a643b72d77ec087fdd9b5c898db5f5edc63 by @samreid  while addressing #104.   PrecipitateParticle previously did not need `dispose`. You added `dispose`, to clean up the tandem registration.   In step 3 of your steps to reproduce, we should see `PrecipitateParticle.dispose` called for each PrecipitateParticle.  I see it called only 3 or 4 times.

Assigning to @samreid to fix.

**Comment by phet-steele** [comment] 2017-08-29 17:13
> Please enumerate the steps required to reproduce this, including which wrapper to use and how to launch it.

@pixelzoom the steps are above. You can do this in the instance-proxies wrapper. After following the steps, there is a little button labeled "launch" just to the right of the sim, above the list of tandems.

**Comment by pixelzoom** [comment] 2017-08-29 17:32
> @pixelzoom the steps are above. You can do this in the instance-proxies wrapper.

OK, so "proxy list" means "use the instance-proxies wrapper".  Not obvious to those of us who aren't familiar with PhET-iO, but I'll roll with it.

**Comment by pixelzoom** [comment] 2017-08-29 17:33
Verified that PrecipitateParticle `dispose` wasn't fully tested when it was added, it's not being called when particles dissolve.   Remains assigned to @samreid to fix.

**Comment by pixelzoom** [comment] 2017-08-29 18:08
In Precipitate.updatePariticles, here's where particles are being removed but not disposed:

```js
80  else if ( numberOfParticles < this.particles.length ) {
        // remove some particles
        var numberToRemove = this.particles.length - numberOfParticles;
        this.particles.splice( this.particles.length - 1 - numberToRemove, numberToRemove );
      }
```

**Comment by pixelzoom** [comment] 2017-08-29 18:15
I'm going to take care of this.

**Comment by pixelzoom** [comment] 2017-08-29 18:24
Before applying the fix, I wanted to verify that I could reproduce the error.  Following the steps in https://github.com/phetsims/phet-io/issues/415, after pressing the "Launch" button, I am seeing errors in the console of the launched sim:

```js
SimIFrameAPI Invocation Error: Error: Assertion failed
    at window.assertions.assertFunction (assert.js:22)
    at ConcentrationSolution.js?bust=1504030987473:108
    at Array.listener (DerivedProperty.js?bust=1504030987473:67)
    at Emitter.emit2 (Emitter.js?bust=1504030987473:200)
    at DerivedProperty._notifyListeners (Property.js?bust=1504030987473:204)
    at DerivedProperty._setAndNotifyListeners (Property.js?bust=1504030987473:193)
    at DerivedProperty.set (Property.js?bust=1504030987473:140)
    at Array.listener (DerivedProperty.js?bust=1504030987473:67)
    at Emitter.emit2 (Emitter.js?bust=1504030987473:200)
    at DerivedProperty._notifyListeners (Property.js?bust=1504030987473:204) Error: Assertion failed
    at window.assertions.assertFunction (http://localhost/~cmalley/GitHub/assert/js/assert.js:22:13)
    at http://localhost/~cmalley/GitHub/beers-law-lab/js/concentration/model/ConcentrationSolution.js?bust=1504030987473:108:19
    at Array.listener (http://localhost/~cmalley/GitHub/axon/js/DerivedProperty.js?bust=1504030987473:67:57)
    at Emitter.emit2 (http://localhost/~cmalley/GitHub/axon/js/Emitter.js?bust=1504030987473:200:49)
    at DerivedProperty._notifyListeners (http://localhost/~cmalley/GitHub/axon/js/Property.js?bust=1504030987473:204:29)
    at DerivedProperty._setAndNotifyListeners (http://localhost/~cmalley/GitHub/axon/js/Property.js?bust=1504030987473:193:14)
    at DerivedProperty.set (http://localhost/~cmalley/GitHub/axon/js/Property.js?bust=1504030987473:140:16)
    at Array.listener (http://localhost/~cmalley/GitHub/axon/js/DerivedProperty.js?bust=1504030987473:67:34)
    at Emitter.emit2 (http://localhost/~cmalley/GitHub/axon/js/Emitter.js?bust=1504030987473:200:49)
    at DerivedProperty._notifyListeners (http://localhost/~cmalley/GitHub/axon/js/Property.js?bust=1504030987473:204:29)
handleSingleInvoke @ SimIFrameAPI.js?bust=1504030987473:122
handleRequest @ SimIFrameAPI.js?bust=1504030987473:179
(anonymous) @ SimIFrameAPI.js?bust=1504030987473:278
postMessage (async)
invokeSequence @ SimIFrameClient.js:296
onSimInitialized @ instance-proxies.html?sim=beers-law-lab&ea:32
onSimInitializedFunction @ SimIFrameClient.js:377
dispatch @ SimIFrameClient.js:168
windowMessageListener @ SimIFrameClient.js:198
postMessage (async)
send @ SimIFrameAPI.js?bust=1504030987473:41
triggerSimInitialized @ SimIFrameAPI.js?bust=1504030987473:295
(anonymous) @ TSim.js?bust=1504030987473:64
emit @ Emitter.js?bust=1504030987473:163
(anonymous) @ Sim.js?bust=1504030987473:726
setTimeout (async)
(anonymous) @ Sim.js?bust=1504030987473:696
setTimeout (async)
runItem @ Sim.js?bust=1504030987473:677
(anonymous) @ Sim.js?bust=1504030987473:692
setTimeout (async)
runItem @ Sim.js?bust=1504030987473:677
(anonymous) @ Sim.js?bust=1504030987473:692
setTimeout (async)
runItem @ Sim.js?bust=1504030987473:677
(anonymous) @ Sim.js?bust=1504030987473:692
setTimeout (async)
runItem @ Sim.js?bust=1504030987473:677
start @ Sim.js?bust=1504030987473:739
(anonymous) @ beers-law-lab-main.js?bust=1504030987473:39
window.phetLaunchSimulation @ SimLauncher.js?bust=1504030987473:50
implementation @ TPhETIO.js?bust=1504030987473:226
invoke @ SimIFrameAPI.js?bust=1504030987473:258
handleSingleInvoke @ SimIFrameAPI.js?bust=1504030987473:119
handleRequest @ SimIFrameAPI.js?bust=1504030987473:161
(anonymous) @ SimIFrameAPI.js?bust=1504030987473:278
postMessage (async)
invoke @ SimIFrameClient.js:270
(anonymous) @ SimIFrameClient.js:507
dispatch @ SimIFrameClient.js:155
windowMessageListener @ SimIFrameClient.js:198
postMessage (async)
send @ SimIFrameAPI.js?bust=1504030987473:41
handleRequest @ SimIFrameAPI.js?bust=1504030987473:164
(anonymous) @ SimIFrameAPI.js?bust=1504030987473:278
postMessage (async)
invoke @ SimIFrameClient.js:270
(anonymous) @ SimIFrameClient.js:506
dispatch @ SimIFrameClient.js:155
windowMessageListener @ SimIFrameClient.js:198
postMessage (async)
send @ SimIFrameAPI.js?bust=1504030987473:41
handleRequest @ SimIFrameAPI.js?bust=1504030987473:164
(anonymous) @ SimIFrameAPI.js?bust=1504030987473:278
postMessage (async)
invoke @ SimIFrameClient.js:270
launch @ SimIFrameClient.js:505
dispatch @ SimIFrameClient.js:155
windowMessageListener @ SimIFrameClient.js:198
postMessage (async)
send @ SimIFrameAPI.js?bust=1504030987473:41
handleRequest @ SimIFrameAPI.js?bust=1504030987473:164
(anonymous) @ SimIFrameAPI.js?bust=1504030987473:278
postMessage (async)
invoke @ SimIFrameClient.js:270
(anonymous) @ SimIFrameClient.js:514
onPhETiOInitialized @ SimIFrameClient.js:397
dispatch @ SimIFrameClient.js:168
windowMessageListener @ SimIFrameClient.js:198
postMessage (async)
send @ SimIFrameAPI.js?bust=1504030987473:41
initialize @ SimIFrameAPI.js?bust=1504030987473:285
doneLoadingImages @ SimLauncher.js?bust=1504030987473:56
launch @ SimLauncher.js?bust=1504030987473:126
(anonymous) @ beers-law-lab-main.js?bust=1504030987473:34
assert.js:21 Assertion failed: mismatched messageIndex, possible start/end mismatch
```

@samreid @zepumph ?

**Comment by pixelzoom** [comment] 2017-08-29 19:05
I fixed disposal in https://github.com/phetsims/beers-law-lab/commit/44331b2005cbf389a2e2137584d57e49cf380b7c.  And after that, the instance-proxies errors went away on "Launch" (no idea why.)

@zepumph would you please verify?

**Comment by zepumph** [comment] 2017-08-29 19:25
I am finding that it is fixed as well. Not only was this problem found from the "Launch" in instance-proxies, but the entire state wrapper was broken. I am seeing that the above commit fixes both. Thank you for expediting this solution @pixelzoom!

**Closed** 2017-08-29 19:27 UTC
Labels: dev:phet-io
