### ISSUE TITLE
Studio may be unable to load when preferences are changed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#321] opened 2023-02-01 20:35 UTC
**Device**
Dell
**OS**
Win 11
**Browser**
Chrome and Firefox
**Problem Description**
For https://github.com/phetsims/qa/issues/889 and https://github.com/phetsims/qa/issues/891.
When loading a sim set up in studio, if there has been a change with the show volume or show solute amount checkboxes in the preferences menu, either in the saved sim or the sim while trying to load, studio will crash with the error shown below. Studio also does not load again even after refreshing. A new tab must be opened.
**Steps to Reproduce**
1. Save a version of the sim in studio
2. Turn on show volume
3. Try to load the saved sim

**Visuals**
<img width="953" alt="loadfile" src="https://user-images.githubusercontent.com/41024075/216157245-33fff033-b640-4d5a-a0a5-21a0ccb70216.png">

**Comment by pixelzoom** [comment] 2023-02-01 20:44
Sounds like something is missing from `dispose`. Probably Text for some control(s). I'm on it.

**Comment by pixelzoom** [comment] 2023-02-01 20:49
Fixed in the above commits. Tested using the above "Steps to Reproduce".

@KatieWoe please verify in master, feel free to close if OK.

**Comment by KatieWoe** [comment] 2023-02-01 21:06
Looks good in master

**Comment by pixelzoom** [comment] 2023-02-06 22:15
Reopening to confirm in https://github.com/phetsims/qa/issues/894. It looks like changes I made during dev testing did not get into the 1.7 release branch.

@KatieWoe can you please test to see if this looks correct in 1.7.0-rc.1.

@samreid @matthew-blackman FYI.

**Comment by pixelzoom** [comment] 2023-02-08 15:18
@KatieWoe @Nancy-Salpepi please reconfirm in 1.7.0-rc.2 for https://github.com/phetsims/qa/issues/894.

**Comment by Nancy-Salpepi** [comment] 2023-02-08 17:26
This is fixed in 1.7.0-rc.2 for BLL and Concentration.

**Closed by Nancy-Salpepi** 2023-02-08 17:26 UTC
Labels: type:bug, status:ready-for-review
