### ISSUE TITLE
CT stateObject provided a public key that is not in the schema: velocity

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/beers-law-lab#311] opened 2023-01-26 16:45 UTC
```
beers-law-lab : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/beers-law-lab/beers-law-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674713901436%22%2C%22timestamp%22%3A1674718180743%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: stateObject provided a public key that is not in the schema: velocity
Error: Assertion failed: stateObject provided a public key that is not in the schema: velocity
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/assert/js/assert.js:28:13)
at assert (IOType.ts:425:30)
at check (IOType.ts:429:85)
at Array.forEach
at forEach (IOType.ts:429:69)
at isStateObjectValid (IOType.ts:413:37)
at isStateObjectValid (IOType.ts:444:9)
at validateStateObject (IOType.ts:281:23)
at toStateObject (PhetioDataHandler.ts:215:54)
at getPhetioData (Emitter.ts:122:17)
id: Bayes Puppeteer
Snapshot from 1/25/2023, 11:18:21 PM

----------------------------------

beers-law-lab : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/beers-law-lab/beers-law-lab_en.html?continuousTest=%7B%22test%22%3A%5B%22beers-law-lab%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1674713901436%22%2C%22timestamp%22%3A1674729294808%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: stateObject provided a public key that is not in the schema: velocity
Error: Assertion failed: stateObject provided a public key that is not in the schema: velocity
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1674713901436/assert/js/assert.js:28:13)
at assert (IOType.ts:425:30)
at check (IOType.ts:429:85)
at Array.forEach
at forEach (IOType.ts:429:69)
at isStateObjectValid (IOType.ts:413:37)
at isStateObjectValid (IOType.ts:444:9)
at validateStateObject (IOType.ts:281:23)
at toStateObject (PhetioDataHandler.ts:215:54)
at getPhetioData (Emitter.ts:122:17)
id: Bayes Puppeteer
Snapshot from 1/25/2023, 11:18:21 PM
```

**Comment by pixelzoom** [comment] 2023-01-26 18:11
Since this is also appearing in Concentration (see https://github.com/phetsims/concentration/issues/63) it is likely related to the first screen (Concentration) in Beer's Law Lab.

**Comment by pixelzoom** [comment] 2023-01-26 18:15
This assertion failure started on 1/25/2023 4:09:35 PM, and has occurred on every CT cycle since. There have been no changes to beers-law-lab, so this is probably a common-code change. @zepumph @samreid does this look familiar?

**Comment by pixelzoom** [comment] 2023-01-26 18:32
This is a seruous regression that introduced 3 weeks ago (!) by the changes described in https://github.com/phetsims/beers-law-lab/issues/265#issuecomment-1369317024.  `SoluteParticleIO` `stateSchema` was missing 2 fields: `velocity` and `acceleration`.   This was fixed in the above commit.

It's concerning that this bug didn't cause PhET-iO to complain at all for 3 weeks. @zepumph @samreid has some improvement been made to PhET-iO?

I'll leave this issue open until I confirm that CT is happy.

**Comment by pixelzoom** [comment] 2023-01-26 18:32
This is a seruous regression that introduced 3 weeks ago (!) by the changes described in https://github.com/phetsims/beers-law-lab/issues/265#issuecomment-1369317024.  `SoluteParticleIO` `stateSchema` was missing 2 fields: `velocity` and `acceleration`.   This was fixed in the above commit.

It's concerning that this bug didn't cause PhET-iO to complain at all for 3 weeks. @zepumph @samreid has some improvement been made to PhET-iO?

I'll leave this issue open until I confirm that CT is happy.

**Comment by zepumph** [comment] 2023-01-26 18:37
>It's concerning that this bug didn't cause PhET-iO to complain at all for 3 weeks. @zepumph @samreid has some improvement been made to PhET-iO?

Yes! We found it last night. It is really scary for us and caused real challenges to how we were thinking about our state migrating updates. See https://github.com/phetsims/tandem/issues/290

**Comment by pixelzoom** [comment] 2023-01-27 16:35
CT is happy. Closing.

**Closed by pixelzoom** 2023-01-27 16:35 UTC
Labels: dev:phet-io, status:ready-for-review, type:automated-testing
