### ISSUE TITLE
Dramatic drop in performance

### ISSUE THREAD

**Issue by samreid** [phetsims/beers-law-lab#112] opened 2015-10-07 17:31 UTC
While I was testing https://github.com/phetsims/together/issues/130 I noticed that the performance of dragging the shaker or dropper is dramatically reduced.  I compared master/built to http://www.colorado.edu/physics/phet/dev/html/concentration/1.2.0-dev.9/ and quantified these results with the profiler.  Chrome Version 45.0.2454.101 (64-bit) on OS X El Capitan dragging the shaker back and forth:

1.2.0-dev.9: 60fps
master/build: 41fps

That version of concentration was published on dev on 01-Sep-2015, there have been 13 commits in the beers-law-lab repo and many commits in common code repos.

**Comment by samreid** [comment] 2015-10-07 18:03
Testing build versions by date:

--before="2015-09-20 13:37" => 41fps
--before="2015-09-10 13:37" => 60fps
--before="2015-09-15 13:37" => 60fps
--before="2015-09-17 13:37" => 60fps
--before="2015-09-19 13:37" => 60fps
--before="2015-09-25 13:37" => 40fps
--before="2015-09-20 13:37" => 60fps ????
--before="2015-09-21 13:37" => 60fps
--before="2015-09-24 13:37" => 40fps
--before="2015-09-22 13:37" => 60fps
--before="2015-09-23 13:37" => 40fps

Checking beers-law-lab and scenery for recent changes before Sept 23, I identified this commit:
https://github.com/phetsims/scenery/commit/c81e47d5494f6b933b854287fb215c1f48184621

If I apply the commit, performance drops.  If I revert the commit, performance skyrockets.  Flagging @jonathanolson and @pixelzoom for discussion, and I'll mark it for "developer-meeting" to keep it on our radar but if we can resolve it before then that would be good too.

**Comment by samreid** [comment] 2015-10-07 19:46
Likewise if I go to master in all repos, i'm seeing 40fps.  Reverting Input.js to scenery7de85ee952d1bc78205b04a921860caafb4a1ec4 speeds it up again.

**Comment by jonathanolson** [comment] 2015-10-07 20:43
So it affects performance in all browsers and platforms?

**Comment by samreid** [comment] 2015-10-07 20:46
Thus far I have only tested Chrome Version 45.0.2454.101 (64-bit) on OS X El Capitan and I recommend broader testing.

**Comment by samreid** [comment] 2015-10-08 02:10
iPad3 iOS9 Safari 13fps dragging the shaker, independent of whether this is before or after Input.js

**Comment by jonathanolson** [comment] 2015-10-08 05:42
I'm not able to reproduce a performance loss between 67dce082a2e44f0348791029150c4a2a7924f686 and c81e47d5494f6b933b854287fb215c1f48184621 on Windows 7 for Firefox/Chrome/IE.

I'd be curious how Firefox on OS X will behave.

**Comment by pixelzoom** [comment] 2015-10-08 17:59
Do we need to put RC testing on hold?

**Comment by pixelzoom** [comment] 2015-10-08 18:01
This is caused by the preventDefault workaround added for iframe in https://github.com/phetsims/scenery/issues/464.

**Comment by pixelzoom** [comment] 2015-10-08 18:05
This is not specific to beers-law-lab, it potentially affects all sims.
This is caused by the preventDefault workaround added for iframe in phetsims/scenery#464.
Performance is much worse in the built version, and doesn't have to be in an iframe.
Only noticed in Chrome on OS X so far, but all platforms have not been tested.

Do we need to put RC testing on hold?

**Comment by samreid** [comment] 2015-10-08 18:05
@samreid demonstrated that the built version is slow, and the requirejs version is super fast.

**Comment by samreid** [comment] 2015-10-08 18:06
@jonathanolson said since the built versions are slower than the requirejs versions, it is much higher priority and he will look into it.

**Comment by pixelzoom** [comment] 2015-10-08 18:06
@ariel-phet says proceed with RC testing. We may need to put publishing on hold until this is resolved.

**Comment by jonathanolson** [comment] 2015-10-10 08:18
https://github.com/phetsims/scenery/issues/406 (layer-fitting hints) would help identify the SVG section that shouldn't be fitted (dynamic movement). In my testing I'm turning off SVG layer fitting so I can dig into the build performance issue.

Timeline for built sim:
![screen shot 2015-10-10 at 2 09 33 am](https://cloud.githubusercontent.com/assets/480878/10410108/05c25204-6ef5-11e5-9158-36e7f4f09703.png)

Timeline for require.js sim:
![screen shot 2015-10-10 at 2 09 02 am](https://cloud.githubusercontent.com/assets/480878/10410110/102edb04-6ef5-11e5-8391-4a48ddd7a83b.png)

There seems to be a main thread "other" computation happening (shown in pie chart) which doesn't show up in the flow. It's pushing frames to ~100ms, whereas we're able to consistently hit the ~16.7ms 60fps with the non-built version.

Will be continuing testing.

**Comment by jonathanolson** [comment] 2015-10-10 08:25
Testing same built version (with disabled SVG layer fitting), but ALSO with preventDefault() called on all non-key events:

![screen shot 2015-10-10 at 2 23 02 am](https://cloud.githubusercontent.com/assets/480878/10410146/f55f33ea-6ef5-11e5-98eb-2df4375a1181.png)

Other testing changes to make the local version more closely match the built version (same header, etc.) haven't resulted in any improvements so far.

**Comment by jonathanolson** [comment] 2015-10-10 08:44
Committed workaround related to https://github.com/phetsims/scenery/issues/464 that calls preventDefault() again on mousemove (most notably) so that we don't have the Chrome performance loss on the dragging. We still keep the previous mousedown (no preventDefault) behavior for https://github.com/phetsims/scenery/issues/464.

Turning off layer fitting on top of this commit makes performance buttery-smooth on the MacBook Air for me. I'll need to complete https://github.com/phetsims/scenery/issues/406 for properly handling the layer fitting (it is triggering every frame, and the browser re-layout is taking a decent chunk of time).

Leaving assigned to me for the layer fitting work.

**Comment by pixelzoom** [comment] 2015-10-13 16:11
@jonathanolson said:
>  I'll need to complete phetsims/scenery#406 for properly handling the layer fitting (it is triggering every frame, and the browser re-layout is taking a decent chunk of time).

This additional issue (phetsims/scenery#406) apparently needs to be fixed before general redeployment of sims.

**Comment by pixelzoom** [comment] 2015-10-13 16:16
@jonathanolson said:
>  I'll need to complete phetsims/scenery#406 for properly handling the layer fitting (it is triggering every frame, and the browser re-layout is taking a decent chunk of time).

This additional issue (phetsims/scenery#406) does NOT need to be fixed before redeploy. It's not something that was caused by the workaround herein, it's been a general performance issue with scenery 0.2 that @jonathanolson has wanted to take care of.

**Comment by pixelzoom** [comment] 2015-10-13 16:20
Applying layer-fitting hint is moved to https://github.com/phetsims/beers-law-lab/issues/113.

Closing this issue, since the performance drop has been addressed.

**Closed by pixelzoom** 2015-10-13 16:20 UTC
Labels: high priority, Summer 2015 redeploy
